# wake up cron
name: Relatorio Automatico

on:
  schedule:
    - cron: '*/10 10-22 * * *'
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar bibliotecas
        run: pip install -r requirements.txt

      - name: Rodar script
        run: python script.py
